apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - nginx-configmap.yaml
  - backend.yaml
  - collector.yaml
  - frontend.yaml

images:
  - name: ghcr.io/apythoneer/usm-backend
    newTag: dev
  - name: ghcr.io/apythoneer/usm-frontend
    newTag: dev
